const puOkCupidSearchQueryModels = {
    London: {
        order_by: "SPECIAL_BLEND",
        gentation: [34],
        gender_tags: 1,
        orientation_tags: null,
        minimum_age: 18,
        maximum_age: 25,
        locid: 453336,
        radius: 25,
        lquery: "",
        location: {
            postal_code: "",
            nameid: 4417328,
            display_state: 0,
            locid: 453336,
            state_code: "H9",
            country_name: "United Kingdom",
            longitude: -11667,
            popularity: 77641,
            state_name: "London, City of",
            default_radius: 25,
            country_code: "UK",
            city_name: "London",
            density: 79034,
            metro_area: 0,
            latitude: 5150000
        },
        located_anywhere: 0,
        last_login: 2678400,
        i_want: "women",
        they_want: "men",
        minimum_height: null,
        maximum_height: null,
        languages: 0,
        speaks_my_language: false,
        ethnicity: [],
        religion: [],
        availability: "any",
        monogamy: "unknown",
        looking_for: ["long_term_dating"],
        smoking: [],
        drinking: [],
        drugs: [],
        answers: [],
        interest_ids: [],
        education: [],
        children: [],
        cats: [],
        dogs: [],
        tagOrder: ["looking_for"],
        save_search: true,
        limit: 18,
        fields: "userinfo,thumbs,percentages,likes,last_contacts,last_login,online"
    }
}

export default puOkCupidSearchQueryModels;